name: CMake

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.distribution }}
    strategy:
      matrix:
        distribution: [ubuntu-18.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Install Alure part 1 - Install dependencies
      run: sudo apt install -y libopenal-dev libvorbis-dev libopusfile-dev libsndfile1-dev

    - name: Install Alure part 2 - Checkout repo
      uses: actions/checkout@v2
      with:
        repository: kcat/alure
        path: './alure'

    - name: Install Alure part 3 - Configure CMake
      run: cmake .. -DCMAKE_INSTALL_INCLUDEDIR=/usr/include -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DALURE_BUILD_EXAMPLES=OFF
      working-directory: ./alure/build

    - name: Install Alure part 4 - Build and install
      run: sudo make -j4 install
      working-directory: ./alure/build

    - name: Install main dependencies
      run: sudo apt install -y build-essential cmake libsdl2-dev libglew-dev libeigen3-dev libassimp-dev libyaml-cpp-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j4
