name: CMake

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ${{ matrix.distribution }}
    strategy:
      matrix:
        distribution: [ubuntu-18.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Update apt
      run: sudo apt update

    - name: Install dependencies
      run: |
        sudo apt install -y build-essential cmake libsdl2-dev libglew-dev libeigen3-dev libassimp-dev libyaml-cpp-dev \
                            libopenal-dev libvorbis-dev libopusfile-dev libsndfile1-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -- -j
